services:
  - type: web
    name: utm-telemetry
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn utm.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DJANGO_DEBUG
        value: "False"
      - key: UTM_SIMULATION_MODE
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
