from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.conf import settings


class DroneTelemetry(models.Model):
    """
    Stores individual telemetry reports from drones.
    Supports real hardware ingestion from ESP32 via TELEM port on Cube Orange+
    as well as simulated flight test data.
    """
    drone_id = models.CharField(
        max_length=64,
        default='drone01',
        db_index=True,
        help_text="Unique identifier for the drone (e.g. drone01)"
    )
    latitude = models.FloatField(
        help_text="GPS Latitude in decimal degrees (-90.0 to 90.0)"
    )
    longitude = models.FloatField(
        help_text="GPS Longitude in decimal degrees (-180.0 to 180.0)"
    )
    altitude = models.FloatField(
        help_text="Altitude in meters above ground level (AGL)"
    )
    heading = models.FloatField(
        help_text="Flight heading in degrees (0.0 to 360.0; 0=North, 90=East, 180=South, 270=West)"
    )
    timestamp = models.DateTimeField(
        help_text="Timestamp reported by telemetry source (e.g., GPS clock via ESP32)"
    )
    received_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text="Server arrival timestamp recorded by Django"
    )
    is_simulated = models.BooleanField(
        default=False,
        db_index=True,
        help_text="True if generated by test simulation engine, False if received from real ESP32 hardware"
    )

    class Meta:
        ordering = ['-received_at']
        verbose_name = 'Drone Telemetry'
        verbose_name_plural = 'Drone Telemetry Records'
        indexes = [
            models.Index(fields=['drone_id', '-received_at']),
            models.Index(fields=['drone_id', 'is_simulated', '-received_at']),
        ]

    def __str__(self):
        source = "SIM" if self.is_simulated else "HW"
        return (
            f"[{self.drone_id}] ({source}) "
            f"Lat: {self.latitude:.4f}°, Lon: {self.longitude:.4f}°, "
            f"Alt: {self.altitude:.1f}m, Hdg: {self.heading:.0f}° @ {self.received_at:%H:%M:%S}"
        )

    @property
    def seconds_since_received(self):
        """Calculates elapsed seconds since server received this packet."""
        delta = timezone.now() - self.received_at
        return max(0.0, delta.total_seconds())

    def is_connected(self, timeout_seconds=None):
        """Returns True if this telemetry packet arrived within the timeout window."""
        if timeout_seconds is None:
            timeout_seconds = getattr(settings, 'TELEMETRY_TIMEOUT_SECONDS', 5)
        return self.seconds_since_received <= timeout_seconds


class PhoneTelemetry(models.Model):
    """
    Stores GPS telemetry received from an Android phone operating in Phone GPS Test Mode.
    Acts as a temporary location provider before physical Cube Orange+ / ESP32 is attached.
    Logically separated from DroneTelemetry to keep future hardware integration clean.
    """
    device_id = models.CharField(
        max_length=64,
        default='phone_test_01',
        db_index=True,
        help_text="Unique phone device identifier (e.g. phone_test_01)"
    )
    latitude = models.FloatField(
        help_text="Phone GPS Latitude in decimal degrees (-90.0 to 90.0)"
    )
    longitude = models.FloatField(
        help_text="Phone GPS Longitude in decimal degrees (-180.0 to 180.0)"
    )
    altitude = models.FloatField(
        null=True,
        blank=True,
        help_text="Altitude in meters above sea level (null if unavailable from phone)"
    )
    heading = models.FloatField(
        null=True,
        blank=True,
        help_text="Compass heading in degrees (0.0 to 360.0; null if unavailable from phone)"
    )
    accuracy = models.FloatField(
        null=True,
        blank=True,
        help_text="Horizontal GPS accuracy in meters"
    )
    speed = models.FloatField(
        null=True,
        blank=True,
        help_text="Speed in meters per second (null if stationary or unavailable)"
    )
    timestamp = models.DateTimeField(
        help_text="Timestamp reported by phone GPS clock"
    )
    received_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text="Server arrival timestamp recorded by Django"
    )
    source = models.CharField(
        max_length=32,
        default='phone_test',
        help_text="Telemetry source identifier (phone_test)"
    )

    class Meta:
        ordering = ['-received_at']
        verbose_name = 'Phone Telemetry'
        verbose_name_plural = 'Phone Telemetry Records'
        indexes = [
            models.Index(fields=['device_id', '-received_at']),
        ]

    def __str__(self):
        acc = f"{self.accuracy:.1f}m" if self.accuracy is not None else "N/A"
        spd = f"{self.speed:.1f}m/s" if self.speed is not None else "N/A"
        return (
            f"[{self.device_id}] (PHONE) "
            f"Lat: {self.latitude:.6f}°, Lon: {self.longitude:.6f}°, "
            f"Acc: {acc}, Spd: {spd} @ {self.received_at:%H:%M:%S}"
        )

    @property
    def seconds_since_received(self):
        """Calculates elapsed seconds since server received this phone packet."""
        delta = timezone.now() - self.received_at
        return max(0.0, delta.total_seconds())

    def is_connected(self, timeout_seconds=None):
        """Returns True if this phone telemetry packet arrived within the timeout window."""
        if timeout_seconds is None:
            timeout_seconds = getattr(settings, 'PHONE_TIMEOUT_SECONDS', 10)
        return self.seconds_since_received <= timeout_seconds


class FlightPermissionRequest(models.Model):
    pilot = models.ForeignKey(User, on_delete=models.CASCADE, related_name='flight_requests', null=True)
    STATUS_CHOICES = (
        ('PENDING', 'Pending'),
        ('APPROVED', 'Approved'),
        ('REJECTED', 'Rejected'),
        ('ACTIVE', 'Active'),
    )
    drone_identifier = models.CharField(max_length=100, default='drone01')
    location_name = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()
    max_altitude = models.FloatField()
    purpose = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    admin_notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Flight Permission Request'
        verbose_name_plural = 'Flight Permission Requests'

    def __str__(self):
        return f"{self.location_name} - {self.get_status_display()}"



class PilotProfile(models.Model):
    STATUS_CHOICES = (
        ('PENDING', 'Pending Approval'),
        ('APPROVED', 'Approved'),
        ('REJECTED', 'Rejected'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='pilot_profile')
    license_number = models.CharField(max_length=100, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Pilot Profile'
        verbose_name_plural = 'Pilot Profiles'

    def __str__(self):
        return f"{self.user.username} - {self.get_status_display()}"

class DroneRegistration(models.Model):
    STATUS_CHOICES = (
        ('PENDING', 'Pending Approval'),
        ('APPROVED', 'Approved'),
        ('REJECTED', 'Rejected'),
    )
    CATEGORY_CHOICES = (
        ('NANO', 'Nano (<= 250g)'),
        ('MICRO', 'Micro (> 250g to <= 2kg)'),
        ('SMALL', 'Small (> 2kg to <= 25kg)'),
        ('MEDIUM', 'Medium (> 25kg to <= 150kg)'),
        ('LARGE', 'Large (> 150kg)'),
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='drones')
    name = models.CharField(max_length=255)
    uin = models.CharField(max_length=50, unique=True, blank=True, null=True, help_text="Unique Identification Number")
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='MICRO')
    max_altitude_m = models.FloatField(default=120.0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Drone Registration'
        verbose_name_plural = 'Drone Registrations'

    def __str__(self):
        return f"{self.name} ({self.uin}) - {self.owner.username}"
