# Generated by Django 4.2.30 on 2026-09-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_id', models.CharField(db_index=True, default='drone01', help_text='Unique identifier for the drone (e.g. drone01)', max_length=64)),
                ('latitude', models.FloatField(help_text='GPS Latitude in decimal degrees (-90.0 to 90.0)')),
                ('longitude', models.FloatField(help_text='GPS Longitude in decimal degrees (-180.0 to 180.0)')),
                ('altitude', models.FloatField(help_text='Altitude in meters above ground level (AGL)')),
                ('heading', models.FloatField(help_text='Flight heading in degrees (0.0 to 360.0; 0=North, 90=East, 180=South, 270=West)')),
                ('timestamp', models.DateTimeField(help_text='Timestamp reported by telemetry source (e.g., GPS clock via ESP32)')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server arrival timestamp recorded by Django')),
            ],
            options={
                'verbose_name': 'Drone Telemetry',
                'verbose_name_plural': 'Drone Telemetry Records',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['drone_id', '-received_at'], name='telemetry_d_drone_i_4cd390_idx')],
            },
        ),
    ]
