# Generated by Django 4.2.30 on 2026-09-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronetelemetry',
            name='is_simulated',
            field=models.BooleanField(db_index=True, default=False, help_text='True if generated by test simulation engine, False if received from real ESP32 hardware'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetry',
            index=models.Index(fields=['drone_id', 'is_simulated', '-received_at'], name='telemetry_d_drone_i_f7924c_idx'),
        ),
    ]
