# Generated by Django 4.2.30 on 2026-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_dronetelemetry_is_simulated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, default='phone_test_01', help_text='Unique phone device identifier (e.g. phone_test_01)', max_length=64)),
                ('latitude', models.FloatField(help_text='Phone GPS Latitude in decimal degrees (-90.0 to 90.0)')),
                ('longitude', models.FloatField(help_text='Phone GPS Longitude in decimal degrees (-180.0 to 180.0)')),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters above sea level (null if unavailable from phone)', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Compass heading in degrees (0.0 to 360.0; null if unavailable from phone)', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Horizontal GPS accuracy in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in meters per second (null if stationary or unavailable)', null=True)),
                ('timestamp', models.DateTimeField(help_text='Timestamp reported by phone GPS clock')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server arrival timestamp recorded by Django')),
                ('source', models.CharField(default='phone_test', help_text='Telemetry source identifier (phone_test)', max_length=32)),
            ],
            options={
                'verbose_name': 'Phone Telemetry',
                'verbose_name_plural': 'Phone Telemetry Records',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['device_id', '-received_at'], name='telemetry_p_device__e7039f_idx')],
            },
        ),
    ]
