# Generated by Django 4.2.30 on 2026-10-02 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telemetry', '0003_phonetelemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin', models.CharField(help_text='Unique Identification Number (UIN) e.g., IND-DRONE-2026-01', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Drone model name or nickname e.g. Quadcopter Alpha', max_length=100)),
                ('category', models.CharField(choices=[('NANO', 'Nano (< 250g)'), ('MICRO', 'Micro (250g - 2kg)'), ('SMALL', 'Small (2kg - 25kg)'), ('MEDIUM', 'Medium (25kg - 150kg)'), ('LARGE', 'Large (> 150kg)')], default='MICRO', max_length=20)),
                ('max_altitude_m', models.FloatField(default=120.0, help_text='Maximum operational altitude rating in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_drones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registered Drone',
                'verbose_name_plural': 'Registered Drones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightPermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_identifier', models.CharField(default='phone_test_01', help_text='Drone or Device ID for telemetry tracking (e.g. phone_test_01 or drone01)', max_length=64)),
                ('location_name', models.CharField(help_text='Target flight area / venue name (e.g. Ludhiana Airspace Zone A)', max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_meters', models.FloatField(default=500.0)),
                ('max_altitude', models.FloatField(default=120.0, help_text='Planned flight altitude (m)')),
                ('duration_minutes', models.IntegerField(default=30, help_text='Planned flight duration in minutes')),
                ('purpose', models.TextField(help_text='Purpose of flight e.g., Telemetry survey, mapping, training')),
                ('status', models.CharField(choices=[('PENDING', 'Pending ATC Approval ⏳'), ('APPROVED', 'Approved by ATC ✅'), ('REJECTED', 'Rejected by ATC ❌')], db_index=True, default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Reason for rejection or special flight conditions issued by ATC', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions', to='telemetry.registereddrone')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flight Permission Request',
                'verbose_name_plural': 'Flight Permission Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AirspaceWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Information / Advisory ℹ️'), ('WARNING', 'Weather / Safety Warning ⚠️'), ('DANGER', 'Airspace Emergency / Hold 🚨')], default='WARNING', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Airspace Warning',
                'verbose_name_plural': 'Airspace Warnings',
                'ordering': ['-created_at'],
            },
        ),
    ]
