# Generated by Django 5.2.8 on 2026-10-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_registereddrone_flightpermissionrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddrone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Registration ⏳'), ('APPROVED', 'Registered ✅'), ('REJECTED', 'Rejected ❌')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
