# Generated by Django 4.2.30 on 2026-10-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_registereddrone_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereddrone',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flightpermissionrequest',
            name='drone',
        ),
        migrations.RemoveField(
            model_name='flightpermissionrequest',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='flightpermissionrequest',
            name='pilot',
        ),
        migrations.RemoveField(
            model_name='flightpermissionrequest',
            name='radius_meters',
        ),
        migrations.RemoveField(
            model_name='flightpermissionrequest',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='flightpermissionrequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightpermissionrequest',
            name='drone_identifier',
            field=models.CharField(default='drone01', max_length=100),
        ),
        migrations.AlterField(
            model_name='flightpermissionrequest',
            name='location_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flightpermissionrequest',
            name='max_altitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='flightpermissionrequest',
            name='purpose',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flightpermissionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='AirspaceWarning',
        ),
        migrations.DeleteModel(
            name='RegisteredDrone',
        ),
    ]
