# Generated by Django 4.2.30 on 2026-10-08 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telemetry', '0006_remove_registereddrone_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilot Profile',
                'verbose_name_plural': 'Pilot Profiles',
            },
        ),
        migrations.CreateModel(
            name='DroneRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uin', models.CharField(blank=True, help_text='Unique Identification Number', max_length=50, null=True, unique=True)),
                ('category', models.CharField(choices=[('NANO', 'Nano (<= 250g)'), ('MICRO', 'Micro (> 250g to <= 2kg)'), ('SMALL', 'Small (> 2kg to <= 25kg)'), ('MEDIUM', 'Medium (> 25kg to <= 150kg)'), ('LARGE', 'Large (> 150kg)')], default='MICRO', max_length=20)),
                ('max_altitude_m', models.FloatField(default=120.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drone Registration',
                'verbose_name_plural': 'Drone Registrations',
            },
        ),
    ]
