# Generated by Django 4.2.30 on 2026-10-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telemetry', '0007_pilotprofile_droneregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermissionrequest',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
